@extends('help._guide')
@section('steps')
    @include('help._step', ['n' => 1, 'title' => 'Install the software from your browser', 'body' => '<p>Plug the ESP32 into a laptop with a USB data cable, open the install page in <strong>Chrome or Edge</strong> and click <strong>Install on my scale</strong>. About a minute, no Arduino IDE, no libraries.</p><p class="text-sm">Bought a ready-made KraalTrac Pro? Skip this step: it comes installed.</p>', 'cta' => [route('firmware.install'), 'Open the install page']])
    @include('help._step', ['n' => 2, 'title' => 'Give it Wi-Fi from your phone', 'body' => '<p>Switch it on. The screen says <em>Wi-Fi setup. On your phone join Wi-Fi: KraalTrac-xxxx</em>. Join that network on your phone; a page pops up (or open <code>192.168.4.1</code>). Pick your farm Wi-Fi or your phone\'s hotspot, type the password, <strong>Save</strong>. It restarts and connects.</p><p>Add more networks later: on the idle screen press <strong>D</strong> then <strong>A</strong>. It remembers up to 5.</p>'])
    @include('help._step', ['n' => 3, 'title' => 'Pair it: six digits', 'body' => '<p>The screen now says <code>Go to farmtech.site /pair and type: 482 913</code>. Open <strong>farmtech.site/pair</strong> on your phone and type the numbers. The page shows a tick when the scale has linked, and the scale says <strong>Paired! Lekker.</strong></p>', 'cta' => [route('pair'), 'Open farmtech.site/pair']])
    @include('help._step', ['n' => 4, 'title' => 'Weigh as usual', 'body' => '<p>Scan a tag (or type the number), pick the weight type, punch in the weight, <code>#</code> to save. Every record is saved on the scale first, then sent. Open <strong>Start weighing</strong> on your phone to watch them arrive.</p><p><strong>New lamb?</strong> The scale fills in the next birthday number for this month (e.g. <code>251004</code>) — press <code>#</code> to accept. <a class="link-u text-char" href="'.route('help.show', 'ids').'">About birthday numbers</a></p>'])
    @include('help._step', ['n' => 5, 'title' => 'No Wi-Fi at the kraal? Easiest first', 'body' => '<ul class="list-disc pl-5 space-y-2"><li><strong>Phone hotspot</strong> — add your phone\'s hotspot to <code>knownNetworks[]</code>. Switch the hotspot on in the kraal and the scale syncs through your phone\'s data as you go.</li><li><strong>Do nothing</strong> — it keeps about 2 000 weighings and syncs by itself the next time it sees Wi-Fi (e.g. back at the house). The top line shows <code>&gt;&gt; 12 QUEUED &lt;&lt;</code> until then.</li><li><strong>Plug in &amp; sync</strong> — plug the scale into a laptop, open Herd Manager in Chrome or Edge → <strong>Sync the scale</strong> → <strong>Connect the scale</strong>. It uploads everything and clears the scale by itself once every record is safe. No program to install.</li><li><strong>Copy &amp; paste</strong> (last resort) — Serial Monitor at 115200, press <code>B</code>, copy the lines between BEGIN and END into Import &amp; export → <strong>Paste from the scale</strong>.</li></ul>', 'cta' => [route('rfid.data.scale'), 'Open Sync the scale →']])
    @include('help._step', ['n' => 6, 'title' => 'Does the scale clear itself?', 'body' => '<p><strong>Yes</strong> — over Wi-Fi and with <em>Plug in &amp; sync</em>, the scale only forgets a record after the website confirmed it was saved, and anything you scanned in the meantime is kept. Only after a copy &amp; paste do you clear it yourself: idle screen → <code>A</code> → PIN → <code>#</code>. Pasting twice is safe — duplicates are skipped.</p><p class="text-sm text-stone">Windows fans can still use <code>sync_from_scale.ps1</code> — it does the same as Plug in &amp; sync.</p>', 'cta' => [route('rfid.readers.firmware', ['device' => 'usb']), '↓ sync_from_scale.ps1']])
    @include('help._step', ['n' => 7, 'title' => 'What the scanner remembers', 'body' => '<p>The scanner keeps a list of your animals (ID, tag, sex, last weight and any warning) in its own memory, refreshed when it\'s online. So even with no signal, a scan shows <code>Sheep: 250912 F</code> and <code>Last 42.5kg 12/09</code>, or a warning like <code>!WITHDRAWAL</code>. After you save, it shows the gain since last time.</p><p>Press <strong>D</strong>, then <strong>D</strong> again, to see how many animals it knows, how full its memory is and roughly how many more weighings fit (usually a couple of thousand). When it gets low, the idle screen says <em>Memory low</em>. It never throws records away: when it\'s full it refuses new ones until you sync.</p>'])
@endsection
@section('aside')
    <div class="rounded-[24px] bg-char text-sand p-6 text-sm">
        <div class="font-headline text-2xl">Scale keys</div>
        <dl class="mt-4 grid grid-cols-[3.5rem_1fr] gap-y-1.5 text-sand/80">
            <dt class="font-num">#</dt><dd>OK / save</dd><dt class="font-num">*</dt><dd>Back / cancel</dd><dt class="font-num">C</dt><dd>Delete a digit</dd>
            <dt class="font-num">A</dt><dd>Decimal point (weight) · Clear queue (idle)</dd><dt class="font-num">B</dt><dd>Send queue over USB (idle)</dd><dt class="font-num">D</dt><dd>Skip (sire/dam) · Device info (idle)</dd>
        </dl>
    </div>
@endsection
