@extends('help._guide')
@section('steps')
    @include('help._step', ['n' => 1, 'title' => 'Start from a template (or your own sheet)', 'body' => '<p>Download a template and fill it in, or use the spreadsheet you already have — we recognise most column names, in English or Afrikaans.</p><div class="grid sm:grid-cols-3 gap-2"><a class="rounded-xl border border-hairline px-4 py-3 hover:border-char" href="'.route('rfid.data.template', 'herd').'"><strong>Herd book</strong><br><span class="text-xs">animals, parents, EBVs</span></a><a class="rounded-xl border border-hairline px-4 py-3 hover:border-char" href="'.route('rfid.data.template', 'scans').'"><strong>Weights</strong><br><span class="text-xs">tag or ID + weight</span></a><a class="rounded-xl border border-hairline px-4 py-3 hover:border-char" href="'.route('rfid.data.template', 'events').'"><strong>Records</strong><br><span class="text-xs">treatments, matings</span></a></div>'])
    @include('help._step', ['n' => 2, 'title' => 'One row per animal (or per weighing)', 'body' => '<div class="overflow-x-auto rounded-xl border border-hairline"><table class="tbl text-xs"><thead><tr><th>visual_id</th><th>sex</th><th>birth_date</th><th>sire</th><th>dam</th><th>weight</th></tr></thead><tbody><tr><td>250912</td><td>F</td><td>14/09/2025</td><td>DVS 222435</td><td>DVS 220120</td><td></td></tr><tr><td>250913</td><td>M</td><td>15/09/2025</td><td>DVS 222435</td><td>2415</td><td></td></tr></tbody></table></div><p>Only the animal ID is required. Dates as <code>dd/mm/yyyy</code>. Leave blanks blank.</p>'])
    @include('help._step', ['n' => 3, 'title' => 'Upload the .xlsx or .csv', 'body' => '<p>Import &amp; export → <strong>Bring data in</strong> → choose the file. Excel files work as-is — no need to "Save as CSV".</p>', 'cta' => [route('rfid.data'), 'Open Import & export']])
    @include('help._step', ['n' => 4, 'title' => 'Check the preview, then import', 'body' => '<p>We show you what we think the file is (herd book, weights or records) and which columns we recognised. Dark = recognised, crossed out = ignored. Change the type if we guessed wrong, then click <strong>Import</strong>.</p><p>Importing the same file twice is safe — same ID means update, never a duplicate.</p>'])
    @include('help._step', ['n' => 5, 'title' => 'Edit in Excel any time', 'body' => '<p>Export the herd book, change it in Excel, and import it again. The export uses exactly the import columns.</p>'])
@endsection
@section('aside')
    <div class="panel p-6 text-sm text-stone"><div class="kpi-label mb-2">Columns we understand</div><p><strong class="text-char">IDs:</strong> visual_id, animal id, dier id, id · <strong class="text-char">Tags:</strong> eid, tag, rfid · <strong class="text-char">Weights:</strong> weight, kg, gewig · <strong class="text-char">Dates:</strong> date, datum, birth_date · <strong class="text-char">Parents:</strong> sire/vaar, dam/moer · <strong class="text-char">Records:</strong> type, product, dose, withdrawal_days</p></div>
@endsection
